EczeCare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('eczema_profile.urls')),
    path('', include('Insights.urls')),
    path('', include('doctor.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path
from .views import doctor_homepage, patient_profile, request_appointment_page, send_request, appointments_page, accept_appointment

urlpatterns = [
    path('doctor_homepage/', doctor_homepage, name="doctor_homepage"),
    path('visit_profile/<slug:patient_username>/',patient_profile),
    path('request_appointment/', request_appointment_page, name="appointment"),
    path('send_request/', send_request),
    path('appointments/', appointments_page, name="doctor_appointments"),
    path('accept_appointment/<int:patient_id>/<int:requested_appointment_id>/', accept_appointment)
]

doctor/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Appointment(models.Model):
    patient = models.ForeignKey(User, on_delete=models.CASCADE)
    appointment_status = models.BooleanField(default=True)

class RequestAppointment(models.Model):
    patient = models.ForeignKey(User, on_delete=models.CASCADE)
    request_status = models.BooleanField(default = False)

class DoctorProfile(models.Model):
    doctor = models.ForeignKey(User, on_delete=models.CASCADE)
    patients = models.ManyToManyField(User, related_name = 'patients')
    appointments = models.ManyToManyField(Appointment)

    def __str__(self):
        return str(self.doctor.username)

templates/configuration-plugin.html
        <div class="custom-template">
			<div class="title">Settings</div>
			<div class="custom-content">
				<div class="switcher">
					<!-- <div class="switch-block">
						<h4>Logo Header</h4>
						<div class="btnSwitch">
							<button type="button" class="changeLogoHeaderColor" data-color="dark"></button>
							<button type="button" class="selected changeLogoHeaderColor" data-color="blue"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="purple"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="light-blue"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="green"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="orange"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="red"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="white"></button>
							<br/>
							<button type="button" class="changeLogoHeaderColor" data-color="dark2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="blue2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="purple2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="light-blue2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="green2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="orange2"></button>
							<button type="button" class="changeLogoHeaderColor" data-color="red2"></button>
						</div>
					</div> -->
					<div class="switch-block">
						<h4>Navbar Header</h4>
						<div class="btnSwitch">
							<button type="button" class="changeTopBarColor" data-color="dark"></button>
							<button type="button" class="changeTopBarColor" data-color="blue"></button>
							<button type="button" class="changeTopBarColor" data-color="purple"></button>
							<button type="button" class="changeTopBarColor" data-color="light-blue"></button>
							<button type="button" class="changeTopBarColor" data-color="green"></button>
							<button type="button" class="changeTopBarColor" data-color="orange"></button>
							<button type="button" class="changeTopBarColor" data-color="red"></button>
							<button type="button" class="changeTopBarColor" data-color="white"></button>
							<br/>
							<button type="button" class="changeTopBarColor" data-color="dark2"></button>
							<button type="button" class="selected changeTopBarColor" data-color="blue2"></button>
							<button type="button" class="changeTopBarColor" data-color="purple2"></button>
							<button type="button" class="changeTopBarColor" data-color="light-blue2"></button>
							<button type="button" class="changeTopBarColor" data-color="green2"></button>
							<button type="button" class="changeTopBarColor" data-color="orange2"></button>
							<button type="button" class="changeTopBarColor" data-color="red2"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Sidebar</h4>
						<div class="btnSwitch">
							<button type="button" class="selected changeSideBarColor" data-color="white"></button>
							<button type="button" class="changeSideBarColor" data-color="dark"></button>
							<button type="button" class="changeSideBarColor" data-color="dark2"></button>
						</div>
					</div>
					<div class="switch-block">
						<h4>Background</h4>
						<div class="btnSwitch">
							<button type="button" class="changeBackgroundColor" data-color="bg2"></button>
							<button type="button" class="changeBackgroundColor selected" data-color="bg1"></button>
							<button type="button" class="changeBackgroundColor" data-color="bg3"></button>
							<button type="button" class="changeBackgroundColor" data-color="dark"></button>
						</div>
					</div>
				</div>
			</div>
			<div class="custom-toggle">
				<i class="flaticon-settings"></i>
			</div>
		</div>

        

templates/footer.html
<footer class="footer">
	<div class="container-fluid">
		<nav class="pull-left">
			<ul class="nav">
				<li class="nav-item">
					<a class="nav-link" 
						target="_blank" 
						href="https://github.com/KamaljeetSahoo/EczeCare">
						EczeCare
					</a>
				</li>
			</ul>
		</nav>
		<div class="copyright ml-auto">
			&copy; <a target="_blank" href="https://github.com/KamaljeetSahoo/EczeCare">Project</a> 
			- coded by <a target="_blank" href="https://github.com/KamaljeetSahoo/EczeCare">KAPS</a>
		</div>				
	</div>
</footer>
</div>

templates/navigation.html
		<div class="main-header">

			<!-- Logo Header -->
			<div class="logo-header ">
				
				<a href="/" class="logo">
					<h1 class="brand-logo">EczeCare</h1>
				</a>
				<button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon">
						<i class="icon-menu"></i>
					</span>
				</button>
				<button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
				<div class="nav-toggle">
					<button class="btn btn-toggle toggle-sidebar">
						<i class="icon-menu"></i>
					</button>
				</div>
			</div>
			<!-- End Logo Header -->

			<!-- Navbar Header -->
			<nav class="navbar navbar-header navbar-expand-lg navbarBG">
				<div class="container-fluid">
					<!-- <div class="collapse" id="search-nav">
						<form class="navbar-left navbar-form nav-search mr-md-3" action="">
							<div class="input-group">
								<div class="input-group-prepend">
									<button type="submit" class="btn btn-search pr-1">
										<i class="fa fa-search search-icon"></i>
									</button>
								</div>
								<input type="text" name="search_tag" placeholder="Search ..." class="form-control" value="{{searched_for}}">
							</div>
						</form>
					</div>
					 -->
					<ul class="navbar-nav topbar-nav ml-md-auto align-items-center">			
						<li class="nav-item dropdown hidden-caret">
							<a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
								<div class="avatar-sm">
									<img src="/static/assets/img/profile.jpg" alt="..." class="avatar-img rounded-circle">
								</div>
							</a>
							<ul class="dropdown-menu dropdown-user animated fadeIn">
								<div class="dropdown-user-scroll scrollbar-outer">
									<li>
										<div class="user-box">
											<div class="avatar-lg"><img src="/static/assets/img/profile.jpg" alt="image profile" class="avatar-img rounded"></div>
											<div class="u-text">
												<h4>
													{{ request.user.username }}
												</h4>
												<p class="text-muted">
													{{ request.user.email }}
												</p>
											</div>
										</div>
									</li>
									<li>
										<div class="dropdown-divider"></div>
										<a class="dropdown-item" href="/logout/">Logout</a>
									</li>
								</div>
							</ul>
						</li>
						<li class="nav-item">
							<i class="fa fa-github"></i>
							<a class="profile-pic">
							</a>
						</li>
					</ul>
				</div>

			</nav>
			<!-- End Navbar -->
        </div>
        

templates/scripts.html
	<!--   Core JS Files   -->
	<script src="/static/assets/js/core/jquery.3.2.1.min.js"></script>
	<script src="/static/assets/js/core/popper.min.js"></script>
	<script src="/static/assets/js/core/bootstrap.min.js"></script>

	<!-- jQuery UI -->
	<script src="/static/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
	<script src="/static/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>

	<!-- jQuery Scrollbar -->
	<script src="/static/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>

	<!-- Chart JS -->
	<script src="/static/assets/js/plugin/chart.js/chart.min.js"></script>

	<!-- jQuery Sparkline -->
	<script src="/static/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>

	<!-- Chart Circle -->
	<script src="/static/assets/js/plugin/chart-circle/circles.min.js"></script>

	<!-- Datatables -->
	<script src="/static/assets/js/plugin/datatables/datatables.min.js"></script>

	<!-- Bootstrap Notify -->
	<script src="/static/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>

	<!-- jQuery Vector Maps -->
	<script src="/static/assets/js/plugin/jqvmap/jquery.vmap.min.js"></script>
	<script src="/static/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>

	<!-- Sweet Alert -->
	<script src="/static/assets/js/plugin/sweetalert/sweetalert.min.js"></script>

	<!-- Atlantis JS -->
    <script src="/static/assets/js/atlantis.min.js"></script>

templates/sidebar.html
<!-- Sidebar -->
<div class="sidebar sidebar-style-2 sidebarBG"> 	
    <div class="sidebar-wrapper scrollbar scrollbar-inner">
        <div class="sidebar-content">

        {% if request.user.is_authenticated %}	
            <div class="user">
                <div class="avatar-sm float-left mr-2">
                    <img src="/static/assets/img/profile.jpg" alt="..." class="avatar-img rounded-circle">
                </div>
                <div class="info">
                    <a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
                        <span>
                            {{ request.user.username }}
                            <span class="user-level">
                                {{ request.user.email }}
                            </span>
                            <span class="caret"></span>
                        </span>
                    </a>
                    <div class="clearfix"></div>

                    <div class="collapse in" id="collapseExample">
                        <ul class="nav">
                            <li>
                                <a href="/logout/">
                                    <span class="link-collapse">Logout</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            {% if request.user.doctorprofile_set.all %}
            <ul class="nav nav-primary">
                <li class="nav-item {% if 'index' in segment %} active {% endif %}">
                    <a  href="/doctor_homepage/">
                        <i class="fas fa-home"></i>
                        <p>Doctor Page</p>
                    </a>
                    <a  href="/appointments/">
                        <i class="fas fa-home"></i>
                        <p>Appointments</p>
                    </a>
                </li> 
                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                </li>
                <li class="mx-4 mt-2">
                    <a target="_blank"
                        href="https://github.com/KamaljeetSahoo/EczeCare" 
                        class="btn btn-block github-btn">
                        <span class="btn-label mr-2 "> <i class="fab fa-github"></i> </span>Github Repository</a> 
                </li>
            </ul>
            {% else %}
            <ul class="nav nav-primary">
                <li class="nav-item {% if 'index' in segment %} active {% endif %}">
                    <a  href="/home/">
                        <i class="fas fa-home"></i>
                        <p>DashBoard</p>
                    </a>
                    <a  href="/analyse/">
                        <i class="fas fa-question"></i>
                        <p>Analyse</p>
                    </a>
                    <a  href="/insights/">
                        <i class="fas fa-chart-bar"></i>
                        <p>Insights</p>
                    </a>
                    <a  href="/ecze_image/">
                        <i class="fas fa-camera"></i>
                        <p>EczeImage</p>
                    </a>
                    <a  href="/triggers/">
                        <i class="fas fa-hospital"></i>
                        <p>Triggers</p>
                    </a>
                    <a  href="/request_appointment/">
                        <i class="fas fa-user"></i>
                        <p>Meet Your Doc</p>
                    </a>
                </li> 
                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                </li>
                <li class="mx-4 mt-2">
                    <a target="_blank"
                        href="https://github.com/KamaljeetSahoo/EczeCare" 
                        class="btn btn-block github-btn">
                        <span class="btn-label mr-2 "> <i class="fab fa-github"></i> </span>Github Repository</a> 
                </li>
            </ul>
            {% endif %}
        {% else %}
            <ul class="nav nav-primary">
                <li class="mx-4 mt-2">
                    <a href="/login/"
                        class="btn btn-danger btn-block">
                        <span class="btn-label mr-2"> <i class="fa fa-user-plus"></i> </span>LOGIN</a> 
                </li>
                <li class="mx-4 mt-2">
                    <a href="/register/" 
                        class="btn btn-danger btn-block">
                        <span class="btn-label mr-2"> <i class="fa fa-user-plus"></i> </span>SIGN UP</a> 
                </li>
            </ul>
        {% endif %}	
        </div>
    </div>
</div>
<!-- End Sidebar -->